print("¡Hola mundo!")
print("¡Hola mundo!")
print("¡Hola mundo!")
binario = int(input("Ingresa 1 o 0"))
if(binario):
    print("¡Hola mundo desde if")
    print("¡Hola mundo desde if")
    print("¡Hola mundo desde if")
print("¡Hola mundo!")
print("¡Hola mundo!")
print("¡Adios mundo!")
